{
  "commonHeader": {
    "timestamp": "2020-05-01T19:38:57.529Z",
    "originatorId": "System",
    "requestId": "remote-ansible-connection-failure",
    "subRequestId": "remote-ansible-connection-failure-1",
    "flags": null
  },
  "actionIdentifiers": {
    "blueprintName": "RT-remote-ansible",
    "blueprintVersion": "1.0.0",
    "actionName": "connection-fail",
    "mode": "sync"
  },
  "status": {
    "code": 500,
    "eventType": "EVENT_COMPONENT_FAILURE",
    "timestamp": "2020-05-01T19:38:57.551Z",
    "errorMessage": "error : ansible-command-logs : Failed to process on remote executor (Connect to localhost:12345 [localhost/127.0.0.1] failed: Connection refused (Connection refused))",
    "message": "failure"
  },
  "payload": {
    "connection-fail-response": {
      "ansible-command-status": "error",
      "ansible-command-logs": "Failed to process on remote executor (Connect to localhost:12345 [localhost/127.0.0.1] failed: Connection refused (Connection refused))"
    }
  }
}
